### ISSUE TITLE
[BUG] index out of range exception when calling MIDA

### ISSUE THREAD

**Issue by caroott** [ZimmerD/QConQuantifier#6]
The MIDA algorithm returns an index out of range exception if it is used on peptide spectrum matches with one or less entries.

Suggestet fix: Skip MIDA when length of PSMs <= 1 in the Pipeline.fs.

**Comment by ZimmerD** [comment]
Thank you for identifying and reporting this behaviour. As far as I am informed Midas should work independently of the Psm number, as the only Psm related parameter is the formula. It seems something is wrong in the way midas is called. Could you dig into this?

**Comment by caroott** [comment]
Something went wrong when calculating the median label efficiency with only one quantified psm present, resulting in a Formula with label efficiency of nan being passed on to MIDA.
Anyways, the correction factor calculation makes only sense when a useful median label efficiency estimation from the data is possible (meaning two or more datapoints). Therefore, label efficiency estimation should only be performed for >1 PSMs.

**Comment by ZimmerD** [comment]
So the problem is not really midas related, which is important since then we would have to fix that issue in BioFSharp, but related to the way midas is called? I would suggest we relable the issue then close it when the pull request is accepted.

**Comment by caroott** [comment]
fixed in #7
